### ISSUE TITLE
Lecture de la sortie standard ralentie

### ISSUE THREAD

**Issue by mmichaud-ign** [ign-gpao/client#11]
Sur le client, dans la méthode read_stdout_process de worker.py
la lecture de la sortie standard se fait dans une boucle qui lit une ligne à la fois
ligne 92 : realtime_output += proc.stdout.readline()

Comme plus loin, la boucle est mise en pause de manière à respecter un intervalle
minimum de 5s avant de lire la ligne suivante, elle ne peut lire tout ce qui sort de 
la sortie standard si celle-ci émet à une fréquence supérieure à 1 ligne / 5 secondes.
Les lignes qui s'accumulent sont remontées d'un coup quand on arrive à la fin du 
traitement puisque là (ligne 97), on lit toutes les lignes d'un coup avec 
proc.stdout.readlines().

Suggestion : utiliser readlines() à chaque iteration de la boucle principale de manière
à lire chaque fois tout ce qui est sorti pendant l'intervalle de 5s.

**Comment by IGNBPesty** [comment]
Le problème de lenteur a été reproduit par Guillaume Liegard sur le LidarHD. On voyait bien sur la page de détail du job le log qui se complète progressivement mais très lentement. Le job en lui-même est rapide mais c'est la mise à jour des logs qui prend du temps.

On avait fait quelques tests avec Jugurtha, en redirigeant la sortie standard du job dans /dev/null on perd les logs mais c'est très rapide.

J'avais tenté de regarder ce qui se passe côté base de données avec HTOP et "select * from pg_stat_activity" mais rien d'anormal.

Ça se comporte comme si le buffer de sortie Python était plein et que le process se met en attente. On avait tenté de lancer le job avec une option Python -U mais sans effet (il me semble).

**Comment by IGNBPesty** [comment]
Double post
