### ISSUE TITLE
Crash si differents utilisateurs lancent le clients (à cause des permissions sur fichier client.log)

### ISSUE THREAD

**Issue by gliegard** [ign-gpao/client#21]
### Comportement

Crash au demarrage du client,
si plusieurs utilisateurs partagent la même machine.

#### Etapes pour reproduire

1. Démarrer le client une fois avec un utilisateur A, et le fermer, un fichier client.log est créé, avec les droits de l'utilisateur A
2. Démarrer le même client avec l'utilisateur B, exception "Permission denied" quand le cleint essaie de supprimer le fichier client.log

**Comment by arnaudbirk** [comment]
A voir pour mettre des droits supplémentaires au fichier client.log à tout le monde sur le fichier au moment de sa création...
