### ISSUE TITLE
Paramétrer le minimum d'espace disque vital

### ISSUE THREAD

**Issue by arnaudbirk** [ign-gpao/client#31]
Dans le cadre du projet LidarHD on a des machines de calcul Linux chez Cégédim avec très peu d'espace disque disponible sur le /var. On dispose d'un répertoire de 25 Go pour Docker et d'un partage Samba de plusieurs To pour les données, donc pas vraiment de problème d'espace, mais le client GPAO refuse de prendre les jobs.

Est-ce qu'on pourrait surcharger le paramètre ?

MIN_AVAILABLE_SPACE = 0

==> 

MIN_AVAILABLE_SPACE = int(os.getenv("GPAO_MIN_AVAILABLE_SPACE", "5"))

**Comment by arnaudbirk** [comment]
De mémoire, le client regarde l'espace disque qu'il possède à l'endroit ou il est installé. Donc normalement si le client est installé sur la partition avec beaucoup d'espace le calcul se fera sur celle-ci.
Si ce n'est pas le comportement observé c'est qu'il y a un bug.

**Comment by IGNBPesty** [comment]
C'est bien ça, c'est le comportement observé, c'est jusque que dans le cas de Cégédim on a des VM avec très peu d'espace disque sur la machine elle-même. 
Les jobs vont utiliser un montage réseau donc on n'a pas besoin d'avoir de l'espace disque en local.
