### ISSUE TITLE
API en HTTPS

### ISSUE THREAD

**Issue by IGNBPesty** [ign-gpao/client#41]
Dans le cas d'une utilisation chez Cégédim, derrière un proxy, nous aurions aimé que les clients GPAO se connecte à l'API via une URL en HTTPS. On a changé la configuration et ça fonctionne sans, donc rien d'urgent. Mais dans le code du client il y a un "http", ce serait pas mal de pouvoir le configurer.

Proposition de modif dans worker.py

URL_API = (
    "http://"
    + os.getenv("URL_API", "localhost")

==>

URL_API = (
    os.getenv("API_PROTOCOL", "http") + "://"
    + os.getenv("URL_API", "localhost")

**Comment by ijeuffrard** [comment]
J'ai l'impression que la PR #34 de Guillaume a déjà réglé le pb depuis la release 0.10.0 du client

**Comment by IGNBPesty** [comment]
Yes, c'est bon pour moi, merci.
