### ISSUE TITLE
Machine avec tag

### ISSUE THREAD

**Issue by TristanFaureIGN** [ign-gpao/client#6]
Il semble que quand on lance un client avec un tag, il apparait avec nom-1 ...
On pourrait la nommer nom-tag ce serait plus facile à s'y retrouver

**Comment by arnaudbirk** [comment]
Dans le client, il y a une option --suffixe qui complète le nom de la machine pour plus de clarté.
Dans le cas d'un lancement avec plusieurs tags, le nom affiché peut vite être un peu lourd à mon avis.
Le -1 devrait disparaître dans une prochaine version.

**Comment by TristanFaureIGN** [comment]
Ok, mais moi, j'ai surtout besoin de savoir les machines qui sont lancées avec le bon tag pour exécuter mes commandes... Du coup, dans la vue HOSTS, on pourrait peut-être simplement rajouter une colone "tags" non?

**Comment by gmaillet** [comment]
Pb constaté sous windows (peut-être pas sous Linux parce que le module multiprocessing ne fonctionne pas de la même façon sur toutes les plateformes).
Le pool crée des process totalement indépendants, dans lesquels la variable HOSTNAME n'est donc pas modifiée. Pour la passer aux sous processus, on peut la passer avec les autres paramètres
`PARAMETERS.append((id_thread, ARGS.tags, HOSTNAME))`
à la place de
`PARAMETERS.append((id_thread, ARGS.tags))`

et 
`url = "session?host=" + parameters[-1]`
à la place de:
`url = "session?host=" + HOSTNAME`
